### ISSUE TITLE
Push current version to PyPI?

### ISSUE THREAD

**Issue by joachimneu** [volkm/bibtex-dblp#5]
Would it be possible to push the current version of this package to PyPI (version there is from 2019). I am building [something](https://github.com/joachimneu/regenbib) that depends on the recent changes, and it seems PyPI doesn't let me upload my package with `bibtex-dblp`'s Github repo as a dependency. Thanks in advance!

**Comment by joachimneu** [comment]
Sorry to bother, any updates regarding this?

I would like to avoid uploading a fork of `bibtex-dblp` to PyPI just to be able to upload my dependent `regenbib` to PyPI. (I don't know how else I can upload my dependent `regenbib` to PyPI; if there is a way, please let me know.)

**Comment by volkm** [comment]
Thanks for the reminder. I found some time and the latest version of `bibtex-dblp` is now available on PyPI.

**Comment by joachimneu** [comment]
Fantastic, thank you!
